In [162]:
import numpy as np 

In [163]:
array = np.array([[[1, 0], [2, 3], [3, 6]], [[1, 0], [2, 3], [3, 6]], [[1, 0], [2, 3], [3, 6]]])

In [164]:
array

array([[[1, 0],
        [2, 3],
        [3, 6]],

       [[1, 0],
        [2, 3],
        [3, 6]],

       [[1, 0],
        [2, 3],
        [3, 6]]])

In [165]:
array.shape

(3, 3, 2)

In [166]:
a = [1, 2, 3, 'hello', 2.2, range]

In [167]:
a = np.array(a, dtype = 'str')

In [168]:
a

array(['1', '2', '3', 'hello', '2.2', "<class 'range'>"], dtype='<U15')

In [169]:
print(type(a[0] + a[1]), a[0] + a[1])

<class 'str'> 12


In [170]:
mat = np.full((2, 4), 0.3)

In [171]:
mat

array([[0.3, 0.3, 0.3, 0.3],
       [0.3, 0.3, 0.3, 0.3]])

In [172]:
mat = np.full((3, 3), 1)

In [173]:
mat

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [174]:
mat = np.eye(4, k=-0, dtype = np.int8)

In [175]:
mat

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]], dtype=int8)

In [176]:
mat = np.random.random((2, 6))

In [177]:
mat

array([[0.42546109, 0.73558795, 0.44343489, 0.38749945, 0.12591689,
        0.89556766],
       [0.45534966, 0.21865135, 0.02329695, 0.33903122, 0.79656268,
        0.59244306]])

In [178]:
mat = np.random.rand(2, 8, 2)

In [179]:
mat

array([[[0.50268215, 0.55620253],
        [0.03661292, 0.95867103],
        [0.92655196, 0.68072216],
        [0.6153209 , 0.50428171],
        [0.23458576, 0.73939499],
        [0.64146048, 0.14909716],
        [0.34919457, 0.20020666],
        [0.25072061, 0.56003023]],

       [[0.81442903, 0.20295333],
        [0.88137712, 0.37886034],
        [0.96688052, 0.56840613],
        [0.9639862 , 0.18922331],
        [0.7517482 , 0.07309609],
        [0.84040243, 0.34402814],
        [0.93494378, 0.7058788 ],
        [0.00446939, 0.03111911]]])

In [180]:
mat_random = np.random.randn(2, 8, 2)

In [181]:
mat

array([[[0.50268215, 0.55620253],
        [0.03661292, 0.95867103],
        [0.92655196, 0.68072216],
        [0.6153209 , 0.50428171],
        [0.23458576, 0.73939499],
        [0.64146048, 0.14909716],
        [0.34919457, 0.20020666],
        [0.25072061, 0.56003023]],

       [[0.81442903, 0.20295333],
        [0.88137712, 0.37886034],
        [0.96688052, 0.56840613],
        [0.9639862 , 0.18922331],
        [0.7517482 , 0.07309609],
        [0.84040243, 0.34402814],
        [0.93494378, 0.7058788 ],
        [0.00446939, 0.03111911]]])

In [182]:
mat = np.full((2, 3), 2)

In [183]:
mat

array([[2, 2, 2],
       [2, 2, 2]])

In [184]:
mat = np.zeros((2, 3))

In [185]:
mat

array([[0., 0., 0.],
       [0., 0., 0.]])

In [186]:
mat = np.zeros_like(mat_random)

In [187]:
mat

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [188]:
X = np.array([[1, 2], [3, 4]])
Y = np.array([[5, 6], [7, 8]])

In [189]:
print(X.shape, Y.shape)

(2, 2) (2, 2)


In [190]:
print(X + Y, np.add(X, Y))

[[ 6  8]
 [10 12]] [[ 6  8]
 [10 12]]


In [191]:
isinstance(X, np.ndarray)

True

In [192]:
print(X - Y, np.subtract(X, Y))

[[-4 -4]
 [-4 -4]] [[-4 -4]
 [-4 -4]]


In [193]:
print(X * Y, np.multiply(X, Y))

[[ 5 12]
 [21 32]] [[ 5 12]
 [21 32]]


In [194]:
print(np.matmul(X, Y), X@Y)

[[19 22]
 [43 50]] [[19 22]
 [43 50]]


In [195]:
print(np.dot(X, Y))

[[19 22]
 [43 50]]


In [196]:
print(X/Y, np.divide(X,Y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]] [[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [197]:
print(np.sqrt(X))

[[1.         1.41421356]
 [1.73205081 2.        ]]


In [198]:
print(np.sqrt(Y))

[[2.23606798 2.44948974]
 [2.64575131 2.82842712]]


In [199]:
(mat_random*5) + 10

array([[[ 6.17886023, 15.34736754],
        [ 6.13582593,  5.72692237],
        [ 4.39478178, 10.77516772],
        [11.77371166,  3.19611892],
        [20.40241776, 10.82992696],
        [ 9.72939645, -2.94463739],
        [ 6.294842  , 10.29350369],
        [15.79771641,  9.38071392]],

       [[12.78640787, 15.39001716],
        [15.32245661, 10.93171085],
        [ 6.07906131, 14.22000679],
        [ 9.43813792, 12.33064658],
        [ 7.62737284, 11.52630529],
        [ 5.15575356, 14.66413492],
        [ 5.17180348,  7.96951385],
        [11.79541393,  3.774652  ]]])

In [200]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([1, 2, 3, 4, 5])

In [201]:
b = b**2

In [202]:
print(a.shape, b.shape)

(5,) (5,)


In [203]:
np.stack((a, b), axis = 1)

array([[ 1,  1],
       [ 2,  4],
       [ 3,  9],
       [ 4, 16],
       [ 5, 25]])

In [204]:
np.stack((a, b), axis = 0)

array([[ 1,  2,  3,  4,  5],
       [ 1,  4,  9, 16, 25]])

In [205]:
np.hstack((a, b))

array([ 1,  2,  3,  4,  5,  1,  4,  9, 16, 25])

In [206]:
np.vstack((a, b))

array([[ 1,  2,  3,  4,  5],
       [ 1,  4,  9, 16, 25]])

In [209]:
print(X, Y)

[[1 2]
 [3 4]] [[5 6]
 [7 8]]


In [212]:
print(np.hstack((X, Y)))
print(np.vstack((X, Y)))

[[1 2 5 6]
 [3 4 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [213]:
print(np.hstack((X, Y)).shape)
print(np.vstack((X, Y)).shape)

(2, 4)
(4, 2)


In [230]:
print(np.hstack((X, Y)).reshape(4, 2))
print(np.vstack((X, Y)))

[[1 2]
 [5 6]
 [3 4]
 [7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [232]:
print(np.hstack((X, Y)).reshape(4, -1))
# -1 works on both rows and column for reshaping the matrix.

[[1 2]
 [5 6]
 [3 4]
 [7 8]]


In [233]:
a = np.random.randint(0, 20, 3)

In [247]:
a

array([ 8, 15,  0])

In [250]:
choice = np.random.choice(a)

In [251]:
choice

15